// 布局配置
export default {
    isDrawer: false,
    primary: "#409eff",
    success: "#67c23a",
    info: "#909399",
    warning: "#e6a23c",
    danger: "#f56c6c",
    topBar: "#ffffff",
    menuBar: "#29384d",
    topBarColor: "#606266",
    menuBarColor: "#e6e6e6",
    isTopBarColorGradual: false,
    isMenuBarColorGradual: false,
    isMenuBarColorHighlight: false,
    isCollapse: false,
    isUniqueOpened: false,
    isFixedHeader: false,
    isCollapse1: false,
    menuWidth: 240,
}