/*
 * @Author: '490912587@qq.com' '490912587@qq.com'
 * @Date: 2022-11-24 09:22:50
 * @LastEditors: '490912587@qq.com' '490912587@qq.com'
 * @LastEditTime: 2022-11-24 09:58:45
 * @FilePath: \backend\src\SeedData\Menu.ts
 * @Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
 */
export const menus = [{
    "Id": 8,
    "Status": 0,
    "MerchantId": 0,
    "CreateTime": "2022-11-23T07:53:21.453Z",
    "UpdateTime": "2022-11-24T01:29:41.000Z",
    "OperatorId": 0,
    "UpdateUserId": 0,
    "IsDelete": false,
    "Version": 5,
    "ParentId": 2,
    "Type": 1,
    "Name": "system.city",
    "Path": "/system/city",
    "Component": "/system/city/index",
    "Redirect": "",
    "Title": "message.router.system.city",
    "IsLink": "",
    "IsHide": false,
    "IsKeepAlive": true,
    "IsAffix": false,
    "IsIframe": false,
    "Permission": "system.city",
    "Icon": "ele-OfficeBuilding",
    "Sort": 101
},
{
    "Id": 7,
    "Status": 0,
    "MerchantId": 0,
    "CreateTime": "2022-11-23T07:50:37.192Z",
    "UpdateTime": "2022-11-24T01:21:19.762Z",
    "OperatorId": 0,
    "UpdateUserId": 0,
    "IsDelete": false,
    "Version": 4,
    "ParentId": 2,
    "Type": 1,
    "Name": "system.dic",
    "Path": "/system/dic",
    "Component": "/system/dic/index",
    "Redirect": "",
    "Title": "message.router.system.dic",
    "IsLink": "",
    "IsHide": false,
    "IsKeepAlive": true,
    "IsAffix": false,
    "IsIframe": false,
    "Permission": "system.dic",
    "Icon": "iconfont icon-zhongyingwen1",
    "Sort": 100
},
{
    "Id": 6,
    "Status": 0,
    "MerchantId": 0,
    "CreateTime": "2022-11-22T13:59:37.445Z",
    "UpdateTime": "2022-11-23T05:56:53.726Z",
    "OperatorId": 0,
    "UpdateUserId": 0,
    "IsDelete": false,
    "Version": 0,
    "ParentId": 0,
    "Type": 0,
    "Name": "personal",
    "Path": "/personal",
    "Component": "personal/index",
    "Redirect": null,
    "Title": "message.router.personal",
    "IsLink": "",
    "IsHide": true,
    "IsKeepAlive": false,
    "IsAffix": false,
    "IsIframe": false,
    "Permission": "personal",
    "Icon": "iconfont icon-gerenzhongxin",
    "Sort": 6
},
{
    "Id": 5,
    "Status": 0,
    "MerchantId": 0,
    "CreateTime": "2022-11-22T13:59:37.445Z",
    "UpdateTime": "2022-11-23T08:05:06.779Z",
    "OperatorId": 0,
    "UpdateUserId": 0,
    "IsDelete": false,
    "Version": 0,
    "ParentId": 2,
    "Type": 1,
    "Name": "system.role",
    "Path": "/system/role",
    "Component": "system/role/index",
    "Redirect": null,
    "Title": "message.router.system.role",
    "IsLink": "",
    "IsHide": false,
    "IsKeepAlive": true,
    "IsAffix": false,
    "IsIframe": false,
    "Permission": "system.role",
    "Icon": "fa fa-street-view",
    "Sort": 5
},
{
    "Id": 4,
    "Status": 0,
    "MerchantId": 0,
    "CreateTime": "2022-11-22T13:59:37.445Z",
    "UpdateTime": "2022-11-23T08:05:03.689Z",
    "OperatorId": 0,
    "UpdateUserId": 0,
    "IsDelete": false,
    "Version": 0,
    "ParentId": 2,
    "Type": 1,
    "Name": "system.user",
    "Path": "/system/user",
    "Component": "system/user/index",
    "Redirect": null,
    "Title": "message.router.system.user",
    "IsLink": null,
    "IsHide": false,
    "IsKeepAlive": true,
    "IsAffix": false,
    "IsIframe": false,
    "Permission": "system.user",
    "Icon": "iconfont icon-icon-",
    "Sort": 4
},
{
    "Id": 3,
    "Status": 0,
    "MerchantId": 0,
    "CreateTime": "2022-11-22T13:59:37.445Z",
    "UpdateTime": "2022-11-23T08:05:00.650Z",
    "OperatorId": 0,
    "UpdateUserId": 0,
    "IsDelete": false,
    "Version": 0,
    "ParentId": 2,
    "Type": 1,
    "Name": "system.menu",
    "Path": "/system/menu",
    "Component": "system/menu/index",
    "Redirect": null,
    "Title": "message.router.system.menu",
    "IsLink": "",
    "IsHide": false,
    "IsKeepAlive": true,
    "IsAffix": false,
    "IsIframe": false,
    "Permission": "system.menu",
    "Icon": "iconfont icon-caidan",
    "Sort": 3
},
{
    "Id": 2,
    "Status": 0,
    "MerchantId": 0,
    "CreateTime": "2022-11-22T13:59:37.445Z",
    "UpdateTime": "2022-11-23T08:05:16.188Z",
    "OperatorId": 0,
    "UpdateUserId": 0,
    "IsDelete": false,
    "Version": 0,
    "ParentId": 0,
    "Type": 0,
    "Name": "system",
    "Path": "/system",
    "Component": "layout/routerView/parent",
    "Redirect": "/system/menu",
    "Title": "message.router.system.system",
    "IsLink": "",
    "IsHide": false,
    "IsKeepAlive": true,
    "IsAffix": false,
    "IsIframe": false,
    "Permission": "system",
    "Icon": "iconfont icon-xitongshezhi",
    "Sort": 2
},
{
    "Id": 1,
    "Status": 0,
    "MerchantId": 0,
    "CreateTime": "2022-11-22T13:59:37.445Z",
    "UpdateTime": "2022-11-22T13:59:37.471Z",
    "OperatorId": 0,
    "UpdateUserId": 0,
    "IsDelete": false,
    "Version": 0,
    "ParentId": 0,
    "Type": 0,
    "Name": "home",
    "Path": "/home",
    "Component": "home/index",
    "Redirect": "",
    "Title": "message.router.home",
    "IsLink": "",
    "IsHide": false,
    "IsKeepAlive": true,
    "IsAffix": true,
    "IsIframe": false,
    "Permission": "home",
    "Icon": "iconfont icon-shouye",
    "Sort": 1
}];